export const IPC = {
  videosList: 'videos:list',
  videosGet: 'videos:get',
  videosPatch: 'videos:patch',
  videosRetry: 'videos:retry',
  collectionsList: 'collections:list',
  collectionsDelete: 'collections:delete',
  collectionsPatch: 'collections:patch',
  importZip: 'import:zip',
  playerResolve: 'player:resolve',
  syncStart: 'sync:start',
  syncStop: 'sync:stop',
  syncStatus: 'sync:status',
  coverFetchStop: 'coverFetch:stop',
  coverFetchStatus: 'coverFetch:status',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsPickSyncFolder: 'settings:pickSyncFolder',
  settingsDetectBrowsers: 'settings:detectBrowsers',
  settingsDataLocation: 'settings:dataLocation',
  dbPurge: 'db:purge',
  dbInfo: 'db:info',
  setupStatus: 'setup:status',
  setupInstall: 'setup:install',
  setupUpdateYtDlp: 'setup:updateYtDlp',
  shellOpenExternal: 'shell:openExternal',
  getAppVersion: 'app:getVersion',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggleMaximize',
  windowClose: 'window:close',
  windowIsMaximized: 'window:isMaximized',
  // events, main -> renderer
  syncEvent: 'sync:event',
  coverFetchEvent: 'coverFetch:event',
  setupProgress: 'setup:progress',
  windowMaximizedChanged: 'window:maximizedChanged'
} as const
